### ISSUE TITLE
Adding a boost increases modifer, not attribute.

### ISSUE THREAD

**Issue by Katiemp013** [Xander-Carroll/xanders-swnr-sheet#3] opened 2024-09-01 07:09 UTC
When adding a boost to the "boost" section under the attribute modifier, it increases the attribute modifier itself rather than the ability score.
I copy and pasted a before and after picture to showcase the issue :) 
![image](https://github.com/user-attachments/assets/9c96e344-9df4-4c8d-8f58-79718587ba20)
![image](https://github.com/user-attachments/assets/4fc00a62-d31c-4dd8-9f77-165180a37c5e)

**Comment by Xander-Carroll** [comment] 2024-09-12 20:48
This was intended behavior when I was designing the sheet. Looking back - I don't know why I thought this was a good idea. The issue was fixed in [v1.1.2](https://github.com/Xander-Carroll/xanders-swnr-sheet/releases/tag/v1.1.2).

Thank you for the amount of detail you gave in your report, it made it very easy to find and fix the issue.

**Closed as completed by Xander-Carroll** 2024-09-12 20:48 UTC
